name: Build and release expo app

on:
  push:
    branches:
      - 'release'

env:
  CI: false

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # - name: Build iOS
      #   run: eas build --platform ios --profile ios-simulator --clear-cache

      # - name: Build Android APK
      #   run: eas build --platform android --profile development --non-interactive --clear-cache

      # - name: Get iOS Build URL
      #   id: get-ios-url
      #   run: echo "ios_url=$(eas build:list --json --limit=1 --platform=ios | jq -r .[0].artifacts.buildUrl)" >> $GITHUB_ENV

      - name: Get Android APK URL
        id: get-apk-url
        run: echo "apk_url=$(eas build:list --json --limit=1 --platform=android --non-interactive | jq -r .[0].artifacts.buildUrl)" >> $GITHUB_ENV

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          to: aman.chahal.1999@gmail.com, aman.0002@icloud.com
          from: Developer
          secure: true
          body: |
            The build job in workflow ${{ github.workflow }} of ${{ github.repository }} has completed.
            - iOS Build URL: ${{ env.ios_url }}
            - Android APK URL: ${{ env.apk_url }}
          ignore_cert: true
          convert_markdown: true

      # - name: Download iOS Build
      #   uses: suisei-cn/actions-download-file@v1
      #   with:
      #     url: ${{ env.ios_url }}
      #     target: public/
      #     auto-match: true

      - name: Download Android APK
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.apk_url }}
          target: public/
          auto-match: true

      - name: List Directory
        run: ls -R public/

      - name: Zip the Files
        uses: thedoctor0/zip-release@master
        with:
          path: public/
          filename: demo-app.zip

      - name: Create Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}

      - name: Upload Asset to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./demo-app.zip
          asset_name: demo-app-v${{ github.run_number }}.zip
          asset_content_type: application/zip

  delete-release:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: dork7/react_native_app
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
